version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: coffee_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: coffee_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-coffee_shop}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: coffee_redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispass} --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: coffee_celery
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-redispass}@redis:6379/0
      - CELERY_BACKEND_URL=redis://:${REDIS_PASSWORD:-redispass}@redis:6379/0
    command: >
      bash -c "celery -A app.core.celery.celery_app worker --loglevel=info"
    healthcheck:
      test: ["CMD", "celery", "inspect", "ping", "-A", "app.core.celery.celery_app"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: coffee_celery_beat
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-redispass}@redis:6379/0
    command: >
      bash -c "celery -A app.core.celery.celery_app beat --loglevel=info"
    restart: unless-stopped

volumes:
  postgres_data:
    name: coffee_shop_postgres_data
  redis_data:
    name: coffee_shop_redis_data

networks:
  default:
    name: coffee_shop_network
